### ISSUE TITLE
Feature Request: Media Page

### ISSUE THREAD

**Issue by Kevinwochan** [ocius/website#62]
Have a page that displays Media Coverage of OCIUS.
E.g ABC News writes an article about us, the page should have a link to that article
Channel 9 News, the page will have a link to the footage

**Comment by r007** [comment]
Hi @Kevinwochan 

Here's the first iteration of design:

https://www.youtube.com/watch?v=fE1uumjO3tM

I implemented tabs to switch between blog posts and media coverage page. On mobile they turn into dropdown. The source for media page is the Yaml file, all the links are taken from ```/src/media/links.yml```, this file has the following format:

```yaml
- url: https://www.your_domain.com/link-to-article
  title: Here goes title for the article
  source: Media source
  date: 2019-07-25
  thumbnail: thumbnails/thumbnail.webp
```

You can see the ```thumbnails``` folder as well. Right now the Yaml file is stuffed with demo content, feel free to replace with real links.

Also, I tried to improve visibility of "About" page. As [research shows](https://www.nngroup.com/articles/scrolling-and-attention/), **74% of the viewing time was spent in the first two screenfuls**. So most users don't see the last sections of this page. That's why I divided this page into sections for quick access.

What do you think?
